import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.jsx',
        './resources/**/*.ts',
        './resources/**/*.tsx',
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-error": "#690005",
                "on-tertiary": "#263143",
                "background": "#0b1326",
                "on-surface": "#dbe2fd",
                "error": "#ffb4ab",
                "surface-variant": "#2d3449",
                "on-secondary": "#68000a",
                "inverse-primary": "#005ac2",
                "surface-dim": "#0b1326",
                "on-secondary-container": "#ffaea8",
                "on-tertiary-container": "#1f2a3c",
                "primary-fixed-dim": "#adc6ff",
                "surface-container-lowest": "#060d20",
                "on-tertiary-fixed-variant": "#3c475a",
                "tertiary-container": "#8691a7",
                "primary-fixed": "#d8e2ff",
                "tertiary": "#bcc7de",
                "surface-container-high": "#222a3e",
                "surface": "#0b1326",
                "tertiary-fixed-dim": "#bcc7de",
                "on-error-container": "#ffdad6",
                "on-surface-variant": "#c2c6d6",
                "secondary": "#ffb3ad",
                "inverse-on-surface": "#283044",
                "on-primary-container": "#00285d",
                "on-secondary-fixed": "#410004",
                "on-primary-fixed-variant": "#004395",
                "on-tertiary-fixed": "#111c2d",
                "surface-container-low": "#131b2e",
                "secondary-fixed-dim": "#ffb3ad",
                "surface-container": "#171f33",
                "on-background": "#dbe2fd",
                "secondary-fixed": "#ffdad7",
                "primary": "#adc6ff",
                "primary-container": "#4d8eff",
                "outline-variant": "#424754",
                "on-primary-fixed": "#001a42",
                "surface-tint": "#adc6ff",
                "surface-bright": "#31394e",
                "tertiary-fixed": "#d8e3fb",
                "secondary-container": "#a40217",
                "on-secondary-fixed-variant": "#930013",
                "surface-container-highest": "#2d3449",
                "outline": "#8c909f",
                "error-container": "#93000a",
                "inverse-surface": "#dbe2fd",
                "on-primary": "#002e6a",

                // Legacy fallback tokens
                "pitch-green": "#CCFF00",
                "accent-cyan": "#00F2FF",
                "accent-pink": "#FF007F",
                "accent-purple": "#8A2BE2",
                "accent-orange": "#FF5500",
                "dashboard-bg": "#0b1326",
                "card-bg": "rgba(30, 41, 59, 0.6)",
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "2xl": "0.75rem",
                "3xl": "1rem",
                "full": "0.75rem"
            },
            spacing: {
                "margin-mobile": "16px",
                "container-max-width": "1280px",
                "container-max": "1280px",
                "gutter": "16px",
                "margin-desktop": "32px",
                "unit": "4px"
            },
            fontFamily: {
                "headline-lg-mobile": ["Archivo Narrow", "sans-serif"],
                "body-md": ["Archivo Narrow", "sans-serif"],
                "headline-lg": ["Archivo Narrow", "sans-serif"],
                "title-md": ["Archivo Narrow", "sans-serif"],
                "display-lg": ["Archivo Narrow", "sans-serif"],
                "label-sm": ["Archivo Narrow", "sans-serif"],
                "archivo": ["Archivo Narrow", "sans-serif"],
                "headline": ["Archivo Narrow", "sans-serif"],
                "body": ["Archivo Narrow", "sans-serif"],
                "label": ["Archivo Narrow", "sans-serif"],
                sans: ['Archivo Narrow', 'Figtree', ...defaultTheme.fontFamily.sans],
                outfit: ["'Outfit'", ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                "headline-lg-mobile": ["24px", { "lineHeight": "30px", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
            },
            animation: {
                'glow-pulse': 'glow-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'subtle-float': 'subtle-float 3s ease-in-out infinite',
                'spin-reverse': 'spin-reverse 2s linear infinite',
            },
            keyframes: {
                'glow-pulse': {
                    '0%, 100%': { opacity: 1, filter: 'brightness(1)' },
                    '50%': { opacity: 0.8, filter: 'brightness(1.5)' },
                },
                'subtle-float': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-5px)' },
                },
                'spin-reverse': {
                    'from': { transform: 'rotate(360deg)' },
                    'to': { transform: 'rotate(0deg)' },
                }
            },
        },
    },
    plugins: [forms],
};

